import Link from 'next/link'
import Head from 'next/head'
import { Alegreya, Monsieur_La_Doulaise, Montserrat} from 'next/font/google'
import cls from "classnames"
import Header from '@/components/Header'

// TODO change font

const alegreya = Alegreya({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })


export default function Home() {

  const myBlogs = 
  [
{    title: 'Something in the way',
post: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi animcupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.' ,
author:'Jamesbo',
date: '12/28/9999',
subtitle: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.",
url:"/something_in_the_way-1",
id:1,
tags:[],
comments:[]
},
{title: 'Nobody knows my sorrow',
post: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi animcupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.' ,
author:'Jamesyboy',
date: '12/28/9199',
subtitle: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.",
url:"/nobody_knows_my_sorrow-2",
id:2,
tags:["happiness", "truth"],
comments:[
  {
    commenter:'',
    comment:'You are the MAN!!',
    date:'12/29/9999',
  }
]

},
{title: 'Winsome Ways of Women',
post: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi animcupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.' ,
author:'Notthisguy',
date: '12/28/9199',
subtitle: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.",
url:"/winsome_ways_of_women_3",
id:3,
tags:[],
comments:[]
}
  ]

  const connectedTitleUrl = (title, id)=>{
      return title.split(' ').join('_') + "-" + id
        
      }
      
  


  return (
    <>
      <Head>
        <title>A Developer&apos;s Devotions and Doings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Header/>
        <div className='text-black grid place-items-center min-h-screen bg-[#0C3BAA] p-[2em] '>
          {/* TODO find exact blue and cream colors (maybe cream gradient?) desired) */}
        

          <div className= 'bg-[#FFFEF2] min-h-[80vh] min-w-[65vw] flex flex-col items-center p-[2em] rounded-2xl'>
            
  {/* CARD - COMPONENTIZE */}
    {
      myBlogs.map((blog)=>{
        return(
          <>
          <Link href={"blogs/" + connectedTitleUrl(blog.title, blog.id)}>
          <div className='bg-[#705721] text-[#FFFEF2] p-4 rounded-xl mb-[1em] min-w-[16em]'>

            <div className={cls(montserrat.className,'bg-brown-500 text-slate-300 uppercase text-center text-xl font-extrabold')}>
              {blog.title}
            </div>
            <div className={cls(alegreya.className,'text-[#ddddda]') }>

            <div className={'text-[#ddddda] text-sm p-2'}>
              {blog.subtitle}
            </div>
                
            <div className={ ' font-bold text-base p-1 min-w-[3em]'}>
              {blog.author}
            </div>
            
            <div className={ ' font-bold text-base p-1 min-w-[3em]'}>
              {blog.date}
            </div>
            </div>
          </div>
          </Link>


          </>
        )
      })
    }
    



          </div>


          </div>
              </main>
    </>
  )
}
